// Shared by navigation and the public directory. Parameter labels reflect the
// actual module inputs/outputs; the directory is a curated index, not certification.
import { Map, Building2, Calculator, Car, ClipboardList, Wallet, ShieldCheck, FileText, History, CalendarClock, Globe2, Box, Ruler, TrendingUp, Sparkles, Gauge, Shapes, DraftingCompass, Activity, Landmark, ShoppingCart, Leaf } from "lucide-react";

const input = (name, unit, basis) => ({ name, unit, basis, kind: "Input" });
const computed = (name, unit, basis) => ({ name, unit, basis, kind: "Calculated" });
const estimate = (name, unit, basis) => ({ name, unit, basis, kind: "Estimate" });
export const WORKSPACE_CATALOG = [
  { id: "site", label: "Site", icon: Map, modules: [
    { id: "plot", name: "Plot & Setbacks", icon: Map, note: "Boundary geometry and development controls.", parameters: [
      input("Plot boundary coordinates", "lat / lng", "Drawn or edited vertices; a new project's boundary is a placeholder."),
      input("Surveyed land boundary points", "point name / lat / lng", "Optional surveyed boundary points from the survey sketch applied directly as the plot polygon."),
      input("Plot length & width", "m", "Editable rectangular plot dimensions when polygon geometry is not used."),
      input("Plot orientation", "° from North", "Site orientation input."),
      input("Plot reference", "text", "Survey or plot reference identifying the project."),
      input("Road-facing edge index", "edge index", "Polygon boundary edge index marked as abutting a public road alongside its road width."),
      input("Road-facing edge widths", "m", "Width recorded per boundary edge; the widest road edge sets the front of the plot."),
      input("Front, rear & side setbacks", "m", "Project development controls; confirm local byelaws."),
      input("Default (unclassified edge) setback", "m", "Applied to boundary edges not marked road-facing."),
      input("Access ring & driveway width", "m", "Site circulation inputs."),
      input("Maximum distance to road", "m", "Tower placement constraint."),
      input("Maximum residential towers", "count", "Blank allows the layout engine to determine what fits."),
      input("Minimum & maximum floors", "floors", "Tower layout bounds."),
      computed("Plot area & buildable envelope", "m²", "Local planar polygon measurement; not a cadastral survey."),
      computed("Plot area in acres & vertex count", "acres / vertices", "Plot area converted to acres (m² ÷ 4,046.86) and active polygon vertex count."),
      computed("Envelope share of plot", "% of plot", "Envelope area against total plot area, with the envelope region count."),
      computed("Per-edge setback classification, length & NBC Part 3 minimum", "class / m", "Boundary edge classification (front, rear, side), measured length, and NBC 2016 Part 3 height-based minimum setback check."),
      computed("Reserved roads, amenities & packable land", "m² / %", "Setbacks, circulation and amenity reservations subtracted from the envelope before packing."),
      computed("Packed towers, units & achieved FAR", "count / units / ratio", "Site layout engine result; each constraint is reported as satisfied or violated."),
      computed("Total building footprint & buildable floor area", "m²", "Sum of packed tower footprints and total buildable floor area across all packed towers."),
      computed("Ground coverage & open space", "%", "Measured from the packed layout, not assumed."),
      computed("Community green / play area", "m²", "Dedicated community open green and play zone reserved inside the setback envelope."),
      computed("Amenity block dimensions, floors & height", "m / floors / m", "Footprint area, width × depth, floor count, and building height for each reserved society amenity block."),
      computed("Pedestrian access links", "m", "Pedestrian circulation links and lengths connecting towers, amenities, and internal access roads."),
      computed("Recommended development controls", "m / ratio / %", "Setbacks, FAR cap and coverage cap derived from plot area and abutting road width; FAR and coverage are indicative pending the local DCR."),
      estimate("Recommended building height, floors & dwelling units", "m / floors / units", "Preliminary building height, floor count, and dwelling unit yield recommended from plot area and widest abutting road width."),
      computed("Genetic refinement run", "generations / score", "Off-grid search telemetry when the layout engine refines the greedy packing."),
      computed("Genetic refinement evaluations, fitness score & NBC spacing check", "evaluations / fitness / status", "Off-grid genetic algorithm evaluation count, seed vs. final fitness score, tower count delta, and NBC Part 3 inter-building clearance verification."),
    ] },
    { id: "planning", name: "Tower & Unit Planning", icon: Building2, note: "Configure each tower separately: floors, building shape, unit mix, 5BHK penthouse, and society amenities.", parameters: [
      input("Tower floor count & height", "floors / m", "Building vertical envelope."),
      input("Building architectural form / shape", "shape", "Curved, cylindrical, chamfered, stepped or rectangular."),
      input("Top-floor 5BHK penthouse", "0 - 2", "Luxury 5BHK penthouses at building pinnacle with private terrace."),
      input("Unit mix per typical floor", "units / m²", "1BHK to 5BHK unit distribution, carpet areas and balconies."),
      input("Society amenities (shared)", "amenities / m²", "Clubhouse, gym, swimming pool, community halls."),
      computed("Tower built-up & carpet area", "m²", "Total built-up and net carpet areas."),
    ] },
    { id: "gis", name: "GIS Intelligence", icon: Globe2, note: "Terrain, surroundings and environmental context.", parameters: [
      input("Study radius", "m", "Surroundings query radius."),
      estimate("Elevation, slope & flood context", "m / %", "Depends on external data coverage and resolution."),
      computed("Sun path", "°", "Location and time-based solar geometry."),
      estimate("Rooftop solar yield", "kWh / year", "Roof area, regional insolation and system assumptions."),
      computed("Terrain min / max / mean / relief", "m", "Elevation samples within the study radius."),
      computed("Diagonal elevation profile & surrounding ring mean", "m", "Elevation profile sampled across the plot diagonal horizontal run and mean elevation of surrounding ground ring."),
      computed("Flood design response", "m", "Nearest water body, elevation delta and minimum plinth height above road level."),
      estimate("Flood risk level & score", "level / /100", "Composite flood hazard level (Low, Moderate, High) and score derived from water proximity and elevation delta."),
      computed("Seismic zone, site class & PGA", "zone / class / g", "City reference with site class from the selected soil; PGA reported for rock and surface."),
      computed("IS 875-3 design wind", "m/s / kN/m²", "Basic speed, terrain-2 design speed and pressure at the design height."),
      estimate("Prevailing & summer wind directions and mean speed", "direction / m/s", "Regional prevailing and summer wind directions, mean wind speed, and natural cross-ventilation orientation guidance."),
      computed("Suitability score & grade", "/100", "Weighted site assessment; a screening aid, not a geotechnical report."),
      computed("Suitability factor breakdown & weights", "score / %", "Individual factor scores, percentage weights, and weighted contributions for slope, flood risk, road access, and surroundings."),
      computed("Buildability constraint flags", "critical / warning / ok", "Automated site buildability status and severity-graded engineering constraint flags."),
      computed("Accessibility & surroundings counts", "m / count", "Nearest road distance and nearby building features from public data."),
      computed("Accessibility score & transit notes", "/100", "Site accessibility score and proximity notes synthesized from detected roads and transit stops."),
      computed("Facade orientation bearings, equinox sun hours & shading guidance", "° / hours / text", "Per-facade compass bearing, equinox direct sun exposure hours, and orientation-specific shading recommendations."),
      computed("Solar system size, saving & payback", "kWp / kWh / INR", "Array size, yearly generation, tariff saving and simple payback."),
      estimate("Usable terrace area, solar insolation & CO₂ avoided", "m² / kWh/m²/yr / tCO₂/yr", "Net usable roof area after core/tank deductions, annual and monthly solar insolation profile, specific yield, and annual CO₂ emissions avoided."),
      estimate("AI site analysis & specialist consultant Q&A", "text", "Natural-language site synthesis and interactive engineering consultant review covering flood, wind, and seismic conditions."),
    ] },
    { id: "township", name: "Township & Master Plan", icon: Landmark, note: "Parcel zoning and mixed-use planning.", parameters: [
      input("Township area", "m²", "Total parcel area the master plan is generated over."),
      input("Mixed-use zoning", "on / off", "Enables retail podium and commercial galleria allocation."),
      input("Parcel allocation", "%", "Land-use distribution across the township."),
      computed("Zoning & circulation", "m²", "Generated master-plan geometry; requires planning review."),
      computed("Land-use shares & permissible FSI", "% / m² / FSI", "Zone-by-zone distribution with the FSI each zone is planned at."),
      computed("Sector breakdown", "units / towers / GLA", "Phased development clusters and their community hubs."),
      computed("Internal right of way", "m", "Internal roadway width in the circulation hierarchy."),
      computed("Pedestrian segregation & gate hierarchy strategy", "strategy", "Master-plan circulation mobility strategy defining pedestrian-vehicular loop segregation, gate hierarchy, dedicated cycle track, and tree verge."),
      estimate("Dwellings, GLA & blended FAR", "units / m² / ratio", "Indicative master-plan yield; align with the statutory development plan."),
      estimate("Township area in acres & estimated population", "acres / persons", "Total township parcel in acres (m² ÷ 4,046.86) and estimated resident population from dwelling unit yield."),
      estimate("Total potential built-up area & open space ratio", "m² / %", "Master-plan total potential built-up area at blended FAR and open space ratio reserved for parks and recreation."),
    ] },
  ] },
  { id: "design", label: "Design", icon: Building2, modules: [
    { id: "autonomous-studio", name: "Quick Generation", icon: Sparkles, note: "Rapid concept schemes from project constraints.", parameters: [
      input("Generation brief", "text", "Site and scheme constraints."),
      estimate("Generated scheme", "concept", "Candidate layout, not an approved construction drawing."),
      input("Target tier", "tier", "Affordable, mid-market or luxury; sets the design assumptions."),
      input("Assumed plot area", "m²", "Plot area the generator designs against."),
      input("Target FAR / FSI", "ratio", "Yield the generator aims at before packing constraints."),
      input("Storeys / height", "floors", "Vertical envelope the generator works within."),
      input("Conversational instruction", "text", "Natural-language mutation of floors, unit mix, parking or setbacks; nothing is applied without being logged."),
      estimate("Generated scheme metrics", "FAR / m² / units / INR", "Achieved FAR, built-up area, unit count and cost of the synthesized scheme."),
      estimate("Multi-agent engineering consensus & overall score", "verdict / /100 / hash", "5-agent interdisciplinary audit (Architect, Structural, MEP, Cost, Statutory/Fire) with overall consensus verdict, composite score, findings, and sign-off hash."),
      computed("Autonomous compliance code audit", "% / checks", "Automated statutory clause scan reporting compliance score, passed/failed check counts, and itemised permissible vs. achieved values per clause."),
      estimate("Autonomous BOQ takeoff & CPWD DSR benchmark variance", "INR / INR per m² / status", "Parametric structural and architectural quantity takeoff reporting total project cost, cost per m², CPWD DSR benchmark rate variance, and itemised line amounts."),
    ] },
    { id: "parking", name: "Parking", icon: Car, note: "Demand, capacity and accessible provision.", parameters: [
      input("Required parking ratio", "spaces / unit", "Project demand factor; check the applicable authority norm."),
      input("Basement levels & area per level", "levels / m²", "Parking capacity inputs."),
      input("Ground-level parking area", "m²", "Surface parking capacity input."),
      input("Area per parking slot", "m² / slot", "Includes aisle allocation as configured."),
      input("Visitor, EV & accessible targets", "%", "Project allocation percentages."),
      input("Visitor, EV & accessible spaces provided", "spaces", "Provided-space inputs."),
      input("Stilt & podium spaces per tower", "spaces", "Building-owned parking supply."),
      input("Ramp slope, width & turning radius", "% / m", "Ramp geometry checks."),
      input("Basement-only supply", "on / off", "Restricts a tower's parking to basement provision."),
      computed("Required, provided & EV bays", "bays", "Demand rounded up to whole parking spaces."),
      computed("Basement & ground slots", "spaces", "Capacity actually provided by each source."),
      computed("Shared parking pool & allocated slots", "spaces", "Combined basement and surface shared parking pool vs. slots allocated across towers and total building-owned slots."),
      computed("Per-building parking demand, supply & compliance", "cars / spaces", "Per-tower residential car demand by carpet-area band, visitor car demand, two-wheeler demand, stilt/podium slots, and shared-pool allocation."),
      computed("Residential basement car, bike & optional pool allocation", "spaces / m²", "Per-tower basement car spaces, two-wheeler spaces, optional purchasable car pool, and basement footprint area."),
      computed("Deficit or headroom", "spaces", "Provided against required; a deficit is a hard failure, not a soft warning."),
      computed("Two-wheeler requirement", "spaces", "Derived from the configured per-tier two-wheeler rules."),
      computed("Layout efficiency", "%", "Share of the parking area that resolves to usable bays."),
      computed("Parking & ramp compliance checks", "pass / fail", "Rule-by-rule validation of total bays, visitor/EV/accessible quotas, ramp slope, ramp width, and turning radius."),
      estimate("Parking optimiser scenarios", "options", "Automated optimisation options to eliminate parking deficits or improve bay efficiency."),
    ] },
    { id: "studio", name: "Generative Studio", icon: Shapes, note: "Apartment planning, AI floor plans, facade, landscape and parking generation.", parameters: [
      input("Tower floors, unit mix & circulation", "floors / units / m", "Project tower, apartment and core inputs."),
      computed("AI floor plans & Vastu checks", "plans / checks", "Saved tower floor layouts shared with Reports."),
      input("Facade, landscape & parking constraints", "settings", "Project-specific generation inputs."),
      estimate("Design alternatives", "concept", "Generated options requiring design review."),
      input("Tower name & typical floor plate", "text / m²", "Per-tower naming and the typical floor plate the planner works on."),
      input("Floor-to-floor height", "m", "Set per tower and used by planning, engineering and the 3D view."),
      input("Unit balcony area", "m²", "Per-unit-type balcony area editable in the typical floor unit mix."),
      input("Corridor width & path length", "m", "Circulation geometry checked against NBC travel and width rules."),
      input("Fire exits per floor & max travel distance", "count / m", "Life-safety inputs checked against supported NBC rules."),
      input("Staircases (count, width, type, location)", "count / m / type", "Stair provision per tower; width feeds the compliance check."),
      input("Lifts (count, capacity, location)", "count / persons", "Lift provision per tower; shortfall is reported as a check."),
      input("Common-area rooms & shared spaces", "m²", "Editable common spaces; their total loads into super built-up area."),
      input("Society amenities (clubhouse, pool, play area)", "m²", "Shared society facilities, entered once per project."),
      input("Room dimensions & doorway widths", "m", "Generated floor-plate rooms, editable per room."),
      input("Room X/Y offsets, room type & doorway connections", "m / type / room", "Per-room coordinate offsets, room function classification, and doorway target connection."),
      input("Landscape open space area", "m²", "Open space area input for generative central park and landscape zoning."),
      input("Parking footprint area & bay layout type", "m² / type", "Footprint area and bay geometry selector (Orthogonal 90° vs. Herringbone 45°/60°) for automated parking grid generation."),
      computed("Unit mix, carpet & built-up area", "units / m²", "Unit types, carpet areas and derived built-up areas from the configured mix."),
      computed("Per-tower height, built-up area & service core per floor", "m / m²", "Tower total height, total built-up area, and empirical service core area per floor."),
      computed("Floor plate room area & schema/adjacency validation", "m² / units passed", "Sum of room areas on the active floor and unit-by-unit schema/adjacency validation results."),
      computed("Vastu & MEP shastra audit score", "% / status", "Directional compliance audit checking Ishanya (NE) living, Agni (SE) kitchen, Nairutya (SW) master suite, and MEP wet-shaft stack grouping."),
      estimate("Facade option catalogue", "options", "Generated facade directions with render prompts; concepts for review."),
      estimate("Facade WWR, shading coefficient, SHGC, energy savings & cost premium", "% / ratio", "Per-archetype Window-to-Wall Ratio, shading coefficient, Solar Heat Gain Coefficient, annual HVAC energy savings, and cost premium."),
      estimate("Landscape zoning", "m² / %", "Park zones, canopy cover, vegetation and softscape share."),
      estimate("Landscape permeability index", "index", "Site stormwater permeability index computed alongside softscape vs. hardscape share and park zone areas."),
      estimate("Parking bay grid", "bays", "Generated orthogonal or herringbone bay layout with aisle width."),
      estimate("Generated parking ECS efficiency, accessible & EV bays, and bay angle", "m²/ECS / bays / °", "Generated parking bay grid metrics including area per ECS, accessible and EV bay counts, driveway aisle width, and bay angle."),
      computed("Smart building recommendations", "opportunities / risks / advisories", "Cross-module synthesis of capacity headroom, parking, compliance, site, cost, and sustainability with quantitative evidence."),
    ] },
    { id: "3d", name: "3D Visualisation", icon: Box, note: "Inspect the spatial arrangement of the scheme.", parameters: [
      input("Tower position & rotation", "m / °", "Placement within the project site."),
      input("View mode, 2D toggle, detailed floors & walk mode", "mode / on-off", "Scene camera mode (Site, Massing, Floor plan, Simple 2D), instanced floor-slab detail toggle, and first-person WASD walk-through mode."),
      input("Solar study season", "date", "Solstice/equinox date selector (21 Jun summer, 21 Mar equinox, 21 Dec winter) driving solar position."),
      input("Hour of day (sun study)", "hour", "Animates the sun position for shadow review."),
      input("Section cut floor", "floor", "Floor the section view cuts through."),
      input("Scene layer visibility toggles", "on / off", "Visibility toggles for tower labels, basement parking levels, balconies, common areas, and compliance violation highlights."),
      computed("Massing & floor stacking", "model", "Visual geometry from current project data."),
      computed("Sun & shadow study", "model", "Solar geometry rendered over the massing."),
      computed("Solar azimuth & altitude at selected hour/season", "°", "Live sun azimuth and altitude computed from site latitude, season, and hour to drive directional shadow casting."),
      computed("Floor plates & structural bays", "model", "Room-by-room plates and bay grid from the planning module."),
      computed("Selected room dimensions & cost", "m / m² / INR", "Room sizes and cost share from the current estimate."),
      computed("Selected tower metrics, cost & compliance violations", "floors / m / m² / INR / checks", "Inspector readout for the selected tower showing floors, height, units, carpet/built-up area, cost per m², estimated tower cost, and rule violations."),
      computed("GIS terrain relief & surrounding context counts", "m / count", "3D terrain mesh relief height, community green area, rendered parking slot count, and nearby OpenStreetMap building count."),
    ] },
  ] },
  { id: "engineering-bim", label: "Engineering & BIM", icon: Ruler, modules: [
    { id: "calculations", name: "Calculations", icon: Calculator, note: "Area statements with arithmetic derivations.", parameters: [
      input("Wall thickness allowance", "ratio", "Configurable estimating factor; explicit zero is preserved."),
      input("Common-area loading", "ratio", "Configured factor for super built-up area."),
      input("FSI factor vs FAR", "×", "Configured multiplier applied to FAR."),
      input("Unit type cycle & units per floor", "tiers / count", "Residential policy the unit mix is generated from."),
      computed("Plot, carpet, built-up & super built-up area", "m²", "Unit areas, floor counts, service-core model and configured loadings."),
      computed("Plot area in acres & unit density per acre", "acres / units/acre", "Plot area in acres and residential unit density alongside population density per hectare."),
      computed("Balcony area", "m²", "Sum of balcony areas across all towers."),
      computed("Footprint, coverage & open space", "m² / %", "Computed from plot and building geometry."),
      computed("FAR, FSI, density & max height", "ratio / units per area / m", "Derived from configured project geometry and unit counts."),
      computed("Units, occupants & density", "count / persons / p per ha", "Unit count, design occupancy and both density measures."),
      computed("Per-tower area & occupancy schedule", "floors / m / units / m² / persons", "Tower-by-tower breakdown of floors, height, units, carpet, built-up, super built-up, footprint, and occupants."),
      computed("Step-by-step area & FAR derivation chains", "formula / m² / ratio", "Explicit arithmetic derivation trees showing each intermediate step for carpet, wall allowance, balcony, service core, built-up, super built-up, and FAR/FSI."),
      computed("FAR capacity headroom", "units", "Maximum units at the FAR cap, remaining headroom and the binding constraint."),
      computed("Capacity growth steps (floors, height, FAR, Δ units & parking deficit)", "table", "Floor-by-floor capacity progression up to the FAR cap showing incremental units, built-up area, parking demand, deficit, and binding constraint."),
      estimate("Explainable AI figure derivation", "text", "On-demand natural-language and formulaic explanation of FAR, ground coverage, total units, parking required, total cost, or seismic base shear."),
    ] },
    { id: "engineering", name: "IS/NBC Engineering", icon: Ruler, note: "Code-referenced preliminary engineering checks and utility sizing inputs.", parameters: [
      input("City", "location", "Selects the configured city reference; confirm project-specific design data."),
      input("Soil type", "classification", "Reference SBC values require geotechnical confirmation."),
      input("Exposure condition", "classification", "Project material durability input."),
      input("Structural system", "classification", "Selects the structural model assumptions."),
      input("Occupancy per unit", "persons / unit", "Project occupancy input used by engineering and utilities."),
      input("Roof area", "m²", "Zero uses the computed footprint in the UI."),
      input("Concrete grade", "MPa", "Configured grade selection."),
      input("Aggregate size & cement type", "mm / type", "Mix design inputs."),
      input("Concrete volume for IS 10262 Mix BOQ link", "m³", "Concrete volume used to scale IS 10262 mix design proportions into total cement bags, sand, aggregate, water, and admixture quantities."),
      input("Slab thickness & structural grid", "mm / m", "Preliminary structural dimensions."),
      input("Wall thickness, finishes load & beam span", "mm / kN/m² / m", "Structural gravity load inputs alongside slab thickness and bay grid dimensions."),
      input("Utility water supply", "L/person/day", "Editable per-capita supply assumption."),
      input("UG & OH tank storage", "days / hours", "Configured storage durations."),
      input("Sump depth & overhead tank count", "m / nos", "Underground sump depth and number of overhead tanks for NBC Part 9 water storage sizing."),
      input("Sewage & WTP factors", "factor", "Project utility-sizing assumptions."),
      input("Annual rainfall & runoff coefficient", "mm / ratio", "Rainwater calculation inputs."),
      input("Rainfall intensity override", "mm/hr", "Stormwater rainfall intensity override for rational-method runoff and rainwater harvesting calculations."),
      input("Connected load", "kW / unit", "Electrical demand input."),
      input("Basement headroom, aisle width & two-wheeler spaces provided", "m / nos", "NBC Part 3/4 basement clear headroom, driveway aisle width, and two-wheeler parking supply."),
      input("Fire lift car width & depth", "m", "Fire lift dimensions checked against supported NBC requirements."),
      input("Passenger lift car width & depth", "mm", "Lift car dimensions used by the NBC lift checks."),
      input("Refuge floors provided & stairwell pressurisation", "nos / on-off", "High-rise fire life-safety inputs per NBC 2016 Part 4."),
      input("Pedestrian ramp slope, clear door width, dual handrails & tactile path", "% / mm / on-off", "NBC Part 3 / Harmonised Guidelines universal accessibility inputs."),
      estimate("Gravity loads & seismic base shear", "kN", "IS 875 / IS 1893 simplified model, not a full structural solver."),
      estimate("Per-tower column load, column size, wind force, seismic weight & base shear", "kN / mm / % W", "Individual tower gravity column load, column section, wind force, seismic weight W, base shear VB, and VB/W ratio."),
      estimate("Foundation & column sizing", "mm / kPa", "Preliminary sizing; verify against geotechnical and structural design."),
      estimate("IS 6403 safe bearing capacity (SBC) reference table", "kN/m² / ° / kN/m³", "Reference Safe Bearing Capacity, angle of internal friction, and soil unit weight across soil classes."),
      computed("Column grid options, beam framing schedule & room-column clash detection", "bays / mm / clashes", "Candidate structural bay grids, beam section framing schedule, and geometric clash check identifying columns inside usable rooms."),
      computed("IS 10262 concrete mix proportions & BOQ material quantities", "kg/m³ / bags / tonnes", "Target mean strength, water-cement ratio, per-m³ mix weights, and total cement bags and aggregate tonnes."),
      estimate("Water demand, STP, WTP & rainwater", "L/day / kLD", "Derived from occupancy, configured demand, rainfall and runoff assumptions."),
      computed("Domestic vs. flushing water demand split", "L/day", "IS 1172 daily water demand split into domestic (90 lpcd) and flushing (45 lpcd) streams."),
      computed("Peak sewage flow, manholes & peak storm runoff", "L/s / count", "Peak sewage discharge, manhole count per IS 1742, and rational-method peak stormwater runoff."),
      computed("Fire & accessibility checks", "checks", "Configured geometry tested against supported NBC rules."),
      computed("Per-floor fire safety checklist", "level / extinguishers / refuge / pass-fail", "Floor-by-floor verification of floor level, travel distance, fire extinguisher count, and refuge area requirement per NBC Part 4."),
      computed("Tank, electrical-room & pump-room sizing", "m³ / m²", "Calculated from project inputs; verify design criteria and applicable standards."),
      computed("Transformer, DG backup & booster head", "kVA / m", "Sized from connected load and building height; verify with the utility."),
      computed("Sewer, stormwater, water-main & power-network sizing", "mm / kVA", "Generated network plan; project-specific hydraulic/electrical verification required."),
      estimate("Embodied carbon, green rating points & plantation plan", "tCO₂e / points / trees", "Material embodied carbon breakdown, auto-credited + manual GRIHA/IGBC green rating points, and mandatory tree plantation count (1 tree per 80 m² plot area)."),
      computed("IS / NBC code reference registry & full-text clause search", "clauses / search hits", "Searchable registry of governing Indian Standard clauses and keyword search across indexed clause text."),
    ] },
    { id: "bim", name: "BIM & CAD Interchange", icon: DraftingCompass, note: "Drawing and model interchange.", parameters: [
      input("CAD geometry & layer mapping", "DXF", "Imported drawing geometry and project mapping."),
      input("Boundary layer selection", "layer", "Drawing layer the imported plot boundary is taken from."),
      computed("DXF layer inventory (entities, closed rings, largest ring area & boundary hint)", "count / m²", "Pre-import inspection of uploaded DXF layers listing entity counts, closed polygon rings, largest ring area, and automatic boundary layer detection."),
      computed("Tower footprints & parking bays (DXF)", "count", "Geometry the exported DXF carries."),
      computed("Buildings & storeys (IFC)", "count", "Model entities the exported IFC4 carries."),
      computed("IFC4 per-tower storey & footprint schedule", "floors / m²", "Georeferenced IFC4 model breakdown showing each exported building's floor count and footprint area."),
      computed("DXF & IFC exports", "files", "Generated from the current model; inspect before downstream use."),
      computed("AutoCAD DWG export", "file", "Native AutoCAD .dwg site plan export alongside .dxf R2018 and georeferenced .ifc (IFC4) exports."),
    ] },
    { id: "digital-twin", name: "Digital Twin & Smart Site", icon: Activity, note: "Construction status and telemetry scenarios.", parameters: [
      input("Milestones & sensor readings", "project data", "Use verified readings; sample telemetry is not a live site feed."),
      input("Device registry & sensor mapping", "devices", "IoT devices registered against project locations."),
      computed("IoT sensor battery, status & live telemetry parameters", "% / status / reading", "Per-device operational status (ONLINE/WARNING), battery level, zone location, hardware model, and live telemetry parameter."),
      estimate("Progress & site indicators", "% / status", "Derived from the provided or simulated dataset."),
      computed("4D BIM floor-by-floor progress breakdown", "status / % / date", "Floor-level construction status (Completed, In Progress, Formwork/Rebar), completion percentage, and milestone date."),
      computed("Schedule & cost performance (SPI / CPI)", "ratio", "Earned-value indices; above 1.0 is ahead of schedule or under budget."),
      estimate("Monte Carlo schedule delay simulation & risk mitigations", "dates / % / +days", "1,000-iteration Monte Carlo completion forecast reporting on-time probability, baseline vs. predicted completion date, and delay impacts."),
      estimate("Smart concrete maturity tracker (Arrhenius equivalent age & strength)", "°C / hrs / °C-hrs / MPa", "ASTM C1074 / IS 456 real-time core and ambient temperature, curing age, equivalent maturity index, estimated vs. target strength, and stripping readiness."),
      computed("Quality index & cube tests", "/100", "Concrete cube test pass rate and the derived quality score."),
      computed("Concrete cube test batch logs (7-day & 28-day strength)", "MPa / status", "IS 456 batch-by-batch 7-day and 28-day cube compressive strength test results and compliance status."),
      computed("Safety man-hours & incidents", "hours", "Recorded safe man-hours; zero-LTI reporting depends on site records."),
      estimate("Predictive facility management & BMS asset health", "hours / % / date", "Building Management System equipment runtime hours, asset health score, operational status, and next preventive maintenance due date."),
    ] },
  ] },
  { id: "cost-procurement", label: "Cost & Procurement", icon: Wallet, modules: [
    { id: "boq", name: "BOQ & Quantities", icon: ClipboardList, note: "Material, labour and equipment schedules.", parameters: [
      input("Quantity ratios & wastage", "ratio / %", "Editable estimating assumptions."),
      input("Editable material, labour & equipment unit rates in BOQ tables", "INR / unit", "Per-item unit rates editable directly inside the Material, Labour (man-days), and Equipment (days) BOQ schedules."),
      computed("Basis built-up area & units", "m² / count", "The basis the quantity take-off is computed against."),
      computed("Line items", "count", "Rows the generated estimate resolves to."),
      estimate("Concrete, steel & finishes", "m³ / kg / m²", "Structural take-off when available; ratio-based estimates are labelled."),
      estimate("Trade labour man-days & equipment operating days", "man-days / days", "Trade-by-trade labour man-days and equipment operating days derived from material quantities and productivity norms."),
      computed("Material, labour & equipment sub-totals", "INR", "Quantities × the project's own rates."),
      computed("BOQ grand total", "INR", "Sum of the three schedules before cost adders."),
      computed("BOQ PDF & Excel workbook exports", "PDF / XLSX", "Direct export of the priced Bill of Quantities as a formatted PDF report or multi-sheet Excel (.xlsx) workbook."),
      estimate("Quantity optimiser scenarios", "options", "Automated value-engineering and quantity optimisation recommendations."),
    ] },
    { id: "cost", name: "Cost Estimation", icon: Wallet, note: "Rates and an itemised project cost.", parameters: [
      input("Material, labour & equipment rates", "INR", "Project rates; defaults are not supplier quotations."),
      input("Overheads, contingency & GST", "%", "Sequential cost adders."),
      input("Wastage allowance", "%", "Estimating allowance applied on top of quantities."),
      input("Currency", "code", "Currency the project is costed in (INR by default)."),
      estimate("Total & per-unit cost", "INR / INR per unit", "Quantities × rates plus configured cost adders."),
      computed("Cost breakdown by head", "INR / %", "Material, labour and equipment shares of the total."),
      computed("Material, labour & equipment cost per m² and per flat", "INR/m² / INR/flat", "Head-by-head breakdown of Material, Labour, and Equipment cost per m² of built-up area and per dwelling unit."),
      computed("Cost per m² built-up", "INR", "Total cost spread over built-up area."),
      estimate("Cost optimisation & value-engineering scenarios", "INR / % saving", "Automated cost optimiser suggestions comparing candidate specification adjustments against current total cost."),
      estimate("AI cost review", "text", "AI audit of unit rates against Indian residential benchmarks flagging key cost drivers and value-engineering savings."),
    ] },
    { id: "procurement", name: "Smart Procurement & Market", icon: ShoppingCart, note: "Procurement scenarios and market context.", parameters: [
      input("Material demand & suppliers", "quantity / records", "Procurement planning inputs."),
      input("Metro market", "city", "Indexed rate basket the market view is read from."),
      input("Educational knowledge-base topic selection", "topic", "Topic selector (FAR, seismic, wind, concrete, rebar, CPM) for interactive civil engineering code explanations."),
      estimate("Price outlook & order schedule", "INR / dates", "Indicative market scenarios, not guaranteed live quotes."),
      computed("Indexed commodity rates", "INR / unit", "Published index rates by metro; confirm with live quotations before ordering."),
      computed("30-day commodity price trend & volatility rating", "% / High-Moderate-Low", "30-day price movement percentage and volatility classification per material in the selected metro."),
      estimate("12-month price forecast series (lower/upper bounds & confidence)", "INR / %", "Monthly projected commodity price with lower/upper confidence bounds, forecast confidence, and monsoon/demand procurement advisory."),
      computed("Pre-qualified supplier scorecards (rating, on-time delivery & credit terms)", "★ / % / days / IS codes", "Tier-1 vendor scorecards reporting quality rating, on-time delivery, credit terms, and certified IS standards."),
      computed("JIT procurement milestones linked to CPM activities", "dates / quantity / activity ID", "Just-In-Time material order and delivery dates synchronized with CPM schedule activity IDs and batch quantities."),
      estimate("Material EOQ, safety stock, reorder point & storage yard allocation", "qty / days / yard area", "Per-material total demand, daily consumption rate, lead time, buffer safety stock, reorder point, Economic Order Quantity (EOQ), and site yard storage allocation."),
      estimate("Tender value & earnest money", "INR", "Indicative tender value and the 1% EMD convention."),
      estimate("Contract structure & escalation", "scenario", "Suggested contract form with an annualised inflation assumption."),
      computed("Tender NIT package (reference no., completion period & compiled sections)", "months / sections / ZIP", "Notice Inviting Tender (NIT) reference number, completion period, compiled CPWD/item-rate tender sections, and downloadable tender package."),
      estimate("Stockout risk & carrying cost", "risk / INR", "Inventory scenario derived from the demand and market assumptions."),
      computed("Dossier readiness", "%", "How much of the procurement documentation set is complete."),
      computed("Statutory clearance agencies & required attachments", "agencies / readiness %", "Agency-by-agency submission readiness (RERA, Fire, Municipal, Environmental) and required attachment checklists."),
      computed("Engineering plugin marketplace & developer REST API specifications", "plugins / endpoints", "Third-party BIM/structural connector catalogue (STAAD.Pro, ETABS, Revit, Primavera) and headless REST API endpoint specifications."),
      computed("Civil engineering educational guides (principle, rule of thumb & pitfalls)", "guide", "Interactive code-referenced engineering tutorials covering core principles, practical rules of thumb, and common mistakes."),
    ] },
    { id: "programme", name: "Programme & CPM", icon: CalendarClock, note: "Dependencies, critical path and schedule options.", parameters: [
      input("Task name, phase, duration & dependency", "text / days / task", "Editable activities and precedence in the project network."),
      input("Start date & target finish", "dates", "Programme timing inputs."),
      input("Mobilisation & blockwork lag", "days / floors", "Schedule assumptions."),
      input("Concrete crew size", "teams", "Number of concurrent concrete teams working at once."),
      input("Crew assignments & task overrides", "crews / days", "Per-task resourcing and duration adjustments."),
      input("Per-task pinned start/finish dates & task cost overrides", "date / INR", "In-place task date pinning, working-day override, crew size override, task cost override, and drag-and-drop row ordering."),
      input("Added & removed tasks", "tasks", "Extra activities and exclusions applied to the generated network."),
      computed("Critical path, float & finish forecast", "days / dates", "CPM on the supplied and configured activity network."),
      computed("Floor cycle & phase breakdown", "days", "Time per typical floor and across project phases."),
      computed("IS 456 minimum prop-removal & curing floor", "calendar days", "Mandatory concrete curing and formwork/prop removal waiting period per floor under IS 456 that cannot be compressed by adding labour."),
      computed("Calendar days & build duration", "days", "Working days converted to the calendar forecast."),
      computed("Implied per-person daily output & pin conflict warnings", "units/day/person / text", "Implied labour productivity when task duration is manually overridden, plus dependency blocker warnings on invalid pinned dates."),
      estimate("Target-finish acceleration cost delta (overtime, crowding & preliminaries)", "INR / days", "Cost impact of accelerating or extending the schedule: overtime premium, work-front crowding loss, and site running preliminaries."),
      computed("Programme budget reconciliation vs. BOQ total", "INR", "Comparison of scheduled task costs, user-added task costs, acceleration premiums, and preliminaries against the BOQ grand total."),
      estimate("Construction equipment planning & logistics fleet (IS 4573 / IS 4925 / IS 5121)", "cranes / m³/h / mixers / hoists / kW", "Tower crane count and hook-time utilisation, batching plant capacity, transit mixers, passenger/material hoists, concrete pump type, connected electrical load, and diesel consumption."),
      estimate("AI programme review", "text", "AI narrative identifying critical-path drivers and realistic schedule recovery opportunities."),
    ] },
    { id: "finance", name: "Feasibility & ROI", icon: TrendingUp, note: "Cash flow and investment scenarios.", parameters: [
      input("Sale rate", "INR / sqft", "Project sales assumption."),
      input("Land, approval & other income", "INR", "Project cost and income inputs."),
      input("Marketing & contingency", "%", "Configured cost assumptions."),
      input("Borrowed share & interest rate", "% / year", "Financing assumptions."),
      input("Discount rate", "% / year", "Annual discount rate editable in financial assumptions for cash-flow valuation."),
      input("Build time, launch & selling period", "months", "Cash-flow timing inputs."),
      input("Pre-sales at launch", "%", "Configured sales assumption."),
      estimate("Revenue, ROI, IRR & payback", "INR / % / months", "Cash-flow model; financial outcomes are forecasts."),
      computed("Gross revenue, total cost & net profit", "INR", "Revenue less cost, on the configured sales and cost bases."),
      computed("Revenue schedule by flat type", "flats / saleable sqft / rate / INR", "Unit-type breakdown of flat count, total saleable super built-up area (sqft), area per flat, asking sale price, and gross revenue."),
      computed("Margin & return on cost", "%", "Profit against revenue and against deployed cost."),
      computed("Peak funding & cash-positive month", "INR / month", "The deepest funding requirement and when the cash flow turns."),
      estimate("Monthly cash-flow curve (inflows, outflows & cumulative cash in hand)", "INR / month", "Month-by-month cash movement and cumulative balance curve over the construction and sales horizon."),
      computed("Break-even units, rate & headroom", "units / INR per sqft / %", "How much stock must sell, at what rate, before the scheme is profitable."),
      computed("Cost per saleable sqft", "INR", "Total cost spread over saleable area."),
      estimate("AI feasibility review", "text", "AI financial assessment of project viability, return drivers, and margin sensitivity."),
    ] },
  ] },
  { id: "deliver-esg", label: "Deliver & ESG", icon: ShieldCheck, modules: [
    { id: "compliance", name: "Compliance", icon: ShieldCheck, note: "Rule-by-rule checks and remaining headroom.", parameters: [
      input("Byelaw thresholds", "rule-specific", "Authority-specific limits and enabled rules."),
      input("Rule parameter, operator & enablement", "selection", "Which computed value a rule tests, whether it is a min or max, and whether the rule is active."),
      input("Custom compliance rule creation (code, label, threshold & unit)", "text / number", "User-defined custom byelaw rules added to the project's compliance rule set."),
      computed("Pass/fail & headroom", "checks / ratio", "Configured checks are not statutory approval."),
      computed("Per-rule actual vs. threshold comparison", "value / status", "Live evaluated actual project value compared against the configured min/max threshold for every rule."),
      computed("Rules evaluated, passed & failed", "count", "Summary of the active rule set."),
      computed("Violation messages & clause references", "text", "Each failure with the governing clause, where one is modelled."),
      computed("Compliance score", "%", "Share of active rules that pass."),
      estimate("AI compliance review", "text", "Plain-language explanation of each failing rule, its statutory intent, and specific design changes to achieve compliance."),
    ] },
    { id: "urban-sustainability", name: "Green Building & ESG", icon: Leaf, note: "Carbon, sustainability and resilience scenarios.", parameters: [
      input("Green checklist & material factors", "points / factors", "Project evidence and emission factors."),
      input("Green certification standard selector (IGBC / GRIHA / LEED v4.1)", "standard", "Selects the green building rating framework (IGBC, GRIHA, or LEED) used to evaluate the project scorecard."),
      estimate("Embodied carbon & green score", "tCO₂e / points", "Indicative assessment, not IGBC or GRIHA certification."),
      estimate("Green certification tier, energy savings & potable water reduction", "tier / %", "Predicted certification tier (Silver, Gold, Platinum, or star rating), total vs. max points by credit category, estimated energy savings, and potable water reduction."),
      computed("Scope 1, 2 & 3 greenhouse gas accounting", "tCO₂e", "Operational and embodied emissions split by scope."),
      computed("Carbon intensity", "kgCO₂e / m²", "Total footprint per unit of built-up area."),
      computed("Annual solar irradiation", "kWh / m² / yr", "Location-based solar resource used by the renewables scenario."),
      computed("30-year lifecycle cost & opex", "INR", "Initial capex plus operating and periodic rehabilitation cost."),
      computed("Lifecycle Capex-to-Opex ratio & Net Present Value (NPV @ 8%)", "ratio / INR", "30-year Capex vs. Opex ratio and discounted lifecycle Net Present Value at 8% discount rate."),
      computed("Resilience score & ESG rating", "/100 / rating", "Composite hazards, infrastructure and worker-welfare assessment."),
      estimate("Multi-hazard disaster risk matrix & structural mitigations", "risk level / zone / mitigation", "Hazard-by-hazard vulnerability rating (seismic, flood, wind, urban heat), zone classification, and structural mitigation measures."),
      estimate("Acoustic attenuation & CPCB daytime noise compliance", "dB(A) / glazing spec", "Curb noise level vs. setback-attenuated front-facade noise level, CPCB daytime residential limit check, and acoustic glazing recommendation."),
      estimate("Ambient air quality (PM2.5 & PM10) & particulate mitigation strategy", "µg/m³ / strategy", "Site ambient PM2.5 and PM10 concentrations, air quality status, and vegetative buffer/dispersion mitigations."),
      computed("Capital rehabilitation schedule", "INR / years", "Planned periodic renewal of building systems."),
      computed("Land value projection", "INR / CAGR", "Current plotted value and the projected 5-year appreciation."),
      estimate("Base land rate, 5-year appreciation table, infrastructure & growth catalysts", "INR/m² / % gain / status", "Current base land rate, year-by-year projected land rate and cumulative capital gain, civic infrastructure adequacy, and transit/zoning value catalysts."),
      estimate("Executive portfolio KPIs (Equity Multiple, GDV, Clearance Index & Safety Factor)", "× / INR / % / factor", "Executive synthesis metrics including project health status, developer IRR, equity multiple, Gross Development Value, gross margin, statutory clearance index, and structural safety factor."),
      estimate("Heavy equipment utilization & multi-factor delay risk buffer", "qty / % / +days", "Allocated equipment fleet utilization, weather/labour/supply-chain delay float impacts, recommended float buffer, and schedule confidence index."),
    ] },
    { id: "data-health", name: "Data Reliability", icon: Gauge, note: "Completeness, freshness and consistency.", parameters: [
      computed("Overall data reliability score & 4-pillar breakdown", "/100", "Composite reliability score and individual 0–100 scores for Completeness, Freshness, Consistency, and Compliance against the 80/100 target threshold."),
      computed("Input coverage & stale results", "% / status", "Checks input availability and version consistency, not engineering correctness."),
      computed("Freshness & consistency artefact state checks", "fresh / stale / ok / mismatch", "Itemised freshness and cross-module consistency checks across plot polygon, packed layout, planning towers, and GIS."),
      computed("Mismatches & missing inputs", "count", "Values that disagree with their source and inputs the engine had to fall back on."),
      computed("Failed compliance rules count", "count", "Count of active compliance rules currently failing, displayed alongside stale artefacts, mismatches, and missing inputs."),
      computed("Engineering warnings & critical findings count by module", "critical / warning count", "Stacked bar breakdown of critical and warning engineering flags raised per module."),
      computed("Reliability scores by source", "%", "Freshness and consistency per data source."),
      computed("Compliance headroom", "ratio", "Distance between computed values and their configured limits."),
    ] },
    { id: "reports", name: "Reports", icon: FileText, note: "Project documents and quantity workbooks.", parameters: [
      input("AI 3D render view style selector", "3D Isometric / Exterior / Interior", "Selects the architectural visualization view type for AI rendering."),
      computed("Executive snapshot strip (8 headline project metrics)", "m² / units / FAR / spaces / INR / checks", "Summary grid embedded in all reports: plot area, built-up area, units, FAR/FSI, parking required/provided, total cost, cost per flat, and compliance score."),
      computed("Project reports & BOQ workbook", "PDF / XLSX", "Generated project snapshots; engineer review required."),
      computed("19 domain-specific PDF dossiers & combined master PDF", "PDF", "Individual PDF reports for every workspace discipline plus a single combined master PDF."),
      computed("Drawing exports", "PNG", "High-resolution site and 3D render exports of the current scheme."),
      computed("CAD exchanges", "DXF / DWG / IFC4", "Model and drawing exports produced from the current project data."),
      computed("Tower floor plan sheets", "PDF", "Saved floor plans included in the report set."),
      estimate("All tower floor plans ZIP archive & AI 3D architectural renders", "ZIP / PNG / prompt", "Batch .zip archive of all tower 2D floor plans and AI-generated 3D isometric, exterior, and interior renders per tower."),
      computed("AI executive summary", "text", "Generated narrative; depends on the configured AI service and is not an approval."),
    ] },
    { id: "collaboration", name: "Versions & Team", icon: History, note: "Project history and shared working.", parameters: [
      input("Team roles & saved versions", "access / revision", "Shared project access and version snapshots."),
      input("Schemes A & B selector for side-by-side comparison", "version ID", "Selects any two saved snapshots (or the live current project) for side-by-side geometric and metric comparison."),
      input("Comments & stage reviews", "text", "Threaded review comments attached to the project and its stages."),
      input("Pinned review comment coordinates, target view & element ID", "x, y, z / view / element", "Spatial pin coordinates, target canvas (2D/3D), and element identifier attached to a design review comment."),
      input("Comment resolution status toggle", "open / resolved", "Marks a spatial review comment or RFI thread as open or resolved."),
      input("Task assignment", "stage / priority / status", "Engineering action items with an owner and workflow state."),
      computed("Activity & scheme comparison", "history / deltas", "Recorded changes and comparisons of selected versions."),
      computed("Side-by-side scaled 2D plan comparison & metric delta table", "SVG / metrics", "Dual-plan SVG comparison drawn at a unified scale alongside a side-by-side metric comparison table across both schemes."),
      estimate("AI scheme comparison recommendation", "text", "AI engineering synthesis explaining practical trade-offs between Scheme A and Scheme B and recommending the stronger option."),
      computed("Project activity audit log", "user / action / timestamp", "Chronological audit trail recording who changed what and when across the project."),
      computed("Stage approval workflow", "status", "Stage gating against the configured review points."),
      computed("Team roster & access roles", "members", "Who holds which role on the project."),
      computed("Workflow automation rules", "rules", "Automations that fire on task and stage transitions."),
    ] },
  ] },
];
export const WORKSPACE_MODULES = WORKSPACE_CATALOG.flatMap(group => group.modules);
export const PARAMETER_COUNT = WORKSPACE_MODULES.reduce((total, module) => total + module.parameters.length, 0);
