// Shared by navigation and the public directory. Parameter labels reflect the
// actual module inputs/outputs; the directory is a curated index, not certification.
import { Map, Building2, Calculator, Car, ClipboardList, Wallet, ShieldCheck, FileText, History, CalendarClock, Globe2, Box, Ruler, TrendingUp, Sparkles, Gauge, Shapes, DraftingCompass, Activity, Landmark, ShoppingCart, Leaf } from "lucide-react";

const input = (name, unit, basis) => ({ name, unit, basis, kind: "Input" });
const computed = (name, unit, basis) => ({ name, unit, basis, kind: "Calculated" });
const estimate = (name, unit, basis) => ({ name, unit, basis, kind: "Estimate" });
export const WORKSPACE_CATALOG = [
  { id: "site", label: "Site", icon: Map, modules: [
    { id: "plot", name: "Plot & Setbacks", icon: Map, note: "Boundary geometry and development controls.", parameters: [
      input("Plot boundary coordinates", "lat / lng", "Drawn or edited vertices; a new project's boundary is a placeholder."), input("Plot length & width", "m", "Editable rectangular plot dimensions when polygon geometry is not used."), input("Plot orientation", "° from North", "Site orientation input."), input("Front, rear & side setbacks", "m", "Project development controls; confirm local byelaws."), input("Access ring & driveway width", "m", "Site circulation inputs."), input("Maximum distance to road", "m", "Tower placement constraint."), input("Maximum residential towers", "count", "Blank allows the layout engine to determine what fits."), input("Minimum & maximum floors", "floors", "Tower layout bounds."), computed("Plot area & buildable envelope", "m²", "Local planar polygon measurement; not a cadastral survey.") ] },
    { id: "gis", name: "GIS Intelligence", icon: Globe2, note: "Terrain, surroundings and environmental context.", parameters: [
      input("Study radius", "m", "Surroundings query radius."), estimate("Elevation, slope & flood context", "m / %", "Depends on external data coverage and resolution."), computed("Sun path", "°", "Location and time-based solar geometry."), estimate("Rooftop solar yield", "kWh / year", "Roof area, regional insolation and system assumptions.") ] },
    { id: "township", name: "Township & Master Plan", icon: Landmark, note: "Parcel zoning and mixed-use planning.", parameters: [
      input("Parcel allocation", "%", "Land-use distribution across the township."), computed("Zoning & circulation", "m²", "Generated master-plan geometry; requires planning review.") ] },
  ] },
  { id: "design", label: "Design", icon: Building2, modules: [
    { id: "autonomous-studio", name: "Quick Generation", icon: Sparkles, note: "Rapid concept schemes from project constraints.", parameters: [input("Generation brief", "text", "Site and scheme constraints."), estimate("Generated scheme", "concept", "Candidate layout, not an approved construction drawing.") ] },
    { id: "parking", name: "Parking", icon: Car, note: "Demand, capacity and accessible provision.", parameters: [
      input("Required parking ratio", "spaces / unit", "Project demand factor; check the applicable authority norm."), input("Basement levels & area per level", "levels / m²", "Parking capacity inputs."), input("Ground-level parking area", "m²", "Surface parking capacity input."), input("Area per parking slot", "m² / slot", "Includes aisle allocation as configured."), input("Visitor, EV & accessible targets", "%", "Project allocation percentages."), input("Visitor, EV & accessible spaces provided", "spaces", "Provided-space inputs."), input("Stilt & podium spaces per tower", "spaces", "Building-owned parking supply."), input("Ramp slope, width & turning radius", "% / m", "Ramp geometry checks."), computed("Required, provided & EV bays", "bays", "Demand rounded up to whole parking spaces.") ] },
    { id: "studio", name: "Generative Studio", icon: Shapes, note: "Apartment planning, AI floor plans, facade, landscape and parking generation.", parameters: [
      input("Tower floors, unit mix & circulation", "floors / units / m", "Project tower, apartment and core inputs."), computed("AI floor plans & Vastu checks", "plans / checks", "Saved tower floor layouts shared with Reports."), input("Facade, landscape & parking constraints", "settings", "Project-specific generation inputs."), estimate("Design alternatives", "concept", "Generated options requiring design review.") ] },
    { id: "3d", name: "3D Visualisation", icon: Box, note: "Inspect the spatial arrangement of the scheme.", parameters: [input("Tower position & rotation", "m / °", "Placement within the project site."), computed("Massing & floor stacking", "model", "Visual geometry from current project data.") ] },
  ] },
  { id: "engineering-bim", label: "Engineering & BIM", icon: Ruler, modules: [
    { id: "calculations", name: "Calculations", icon: Calculator, note: "Area statements with arithmetic derivations.", parameters: [
      input("Wall thickness allowance", "ratio", "Configurable estimating factor; explicit zero is preserved."), input("Common-area loading", "ratio", "Configured factor for super built-up area."), input("FSI factor vs FAR", "×", "Configured multiplier applied to FAR."), computed("Plot, carpet, built-up & super built-up area", "m²", "Unit areas, floor counts, service-core model and configured loadings."), computed("Footprint, coverage & open space", "m² / %", "Computed from plot and building geometry."), computed("FAR, FSI, density & max height", "ratio / units per area / m", "Derived from configured project geometry and unit counts.") ] },
    { id: "engineering", name: "IS/NBC Engineering", icon: Ruler, note: "Code-referenced preliminary engineering checks and utility sizing inputs.", parameters: [
      input("City", "location", "Selects the configured city reference; confirm project-specific design data."), input("Soil type", "classification", "Reference SBC values require geotechnical confirmation."), input("Exposure condition", "classification", "Project material durability input."), input("Structural system", "classification", "Selects the structural model assumptions."), input("Occupancy per unit", "persons / unit", "Project occupancy input used by engineering and utilities."), input("Roof area", "m²", "Zero uses the computed footprint in the UI."), input("Concrete grade", "MPa", "Configured grade selection."), input("Aggregate size & cement type", "mm / type", "Mix design inputs."), input("Slab thickness & structural grid", "mm / m", "Preliminary structural dimensions."), input("Utility water supply", "L/person/day", "Editable per-capita supply assumption."), input("UG & OH tank storage", "days / hours", "Configured storage durations."), input("Sewage & WTP factors", "factor", "Project utility-sizing assumptions."), input("Annual rainfall & runoff coefficient", "mm / ratio", "Rainwater calculation inputs."), input("Connected load", "kW / unit", "Electrical demand input."), estimate("Gravity loads & seismic base shear", "kN", "IS 875 / IS 1893 simplified model, not a full structural solver."), estimate("Foundation & column sizing", "mm / kPa", "Preliminary sizing; verify against geotechnical and structural design."), estimate("Water demand, STP, WTP & rainwater", "L/day / kLD", "Derived from occupancy, configured demand, rainfall and runoff assumptions."), computed("Fire & accessibility checks", "checks", "Configured geometry tested against supported NBC rules."), computed("Tank, electrical-room & pump-room sizing", "m³ / m²", "Calculated from project inputs; verify design criteria and applicable standards."), computed("Sewer, stormwater, water-main & power-network sizing", "mm / kVA", "Generated network plan; project-specific hydraulic/electrical verification required.") ] },
    { id: "bim", name: "BIM & CAD Interchange", icon: DraftingCompass, note: "Drawing and model interchange.", parameters: [input("CAD geometry & layer mapping", "DXF", "Imported drawing geometry and project mapping."), computed("DXF & IFC exports", "files", "Generated from the current model; inspect before downstream use.") ] },
    { id: "digital-twin", name: "Digital Twin & Smart Site", icon: Activity, note: "Construction status and telemetry scenarios.", parameters: [input("Milestones & sensor readings", "project data", "Use verified readings; sample telemetry is not a live site feed."), estimate("Progress & site indicators", "% / status", "Derived from the provided or simulated dataset.") ] },
  ] },
  { id: "cost-procurement", label: "Cost & Procurement", icon: Wallet, modules: [
    { id: "boq", name: "BOQ & Quantities", icon: ClipboardList, note: "Material, labour and equipment schedules.", parameters: [input("Quantity ratios & wastage", "ratio / %", "Editable estimating assumptions."), estimate("Concrete, steel & finishes", "m³ / kg / m²", "Structural take-off when available; ratio-based estimates are labelled.") ] },
    { id: "cost", name: "Cost Estimation", icon: Wallet, note: "Rates and an itemised project cost.", parameters: [input("Material, labour & equipment rates", "INR", "Project rates; defaults are not supplier quotations."), input("Overheads, contingency & GST", "%", "Sequential cost adders."), estimate("Total & per-unit cost", "INR / INR per unit", "Quantities × rates plus configured cost adders.") ] },
    { id: "procurement", name: "Smart Procurement & Market", icon: ShoppingCart, note: "Procurement scenarios and market context.", parameters: [input("Material demand & suppliers", "quantity / records", "Procurement planning inputs."), estimate("Price outlook & order schedule", "INR / dates", "Indicative market scenarios, not guaranteed live quotes.") ] },
    { id: "programme", name: "Programme & CPM", icon: CalendarClock, note: "Dependencies, critical path and schedule options.", parameters: [input("Task name, phase, duration & dependency", "text / days / task", "Editable activities and precedence in the project network."), input("Start date & target finish", "dates", "Programme timing inputs."), input("Mobilisation & blockwork lag", "days / floors", "Schedule assumptions."), input("Crew assignments & task overrides", "crews / days", "Per-task resourcing and duration adjustments."), computed("Critical path, float & finish forecast", "days / dates", "CPM on the supplied and configured activity network.") ] },
    { id: "finance", name: "Feasibility & ROI", icon: TrendingUp, note: "Cash flow and investment scenarios.", parameters: [input("Sale rate", "INR / sqft", "Project sales assumption."), input("Land, approval & other income", "INR", "Project cost and income inputs."), input("Marketing & contingency", "%", "Configured cost assumptions."), input("Borrowed share & interest rate", "% / year", "Financing assumptions."), input("Build time, launch & selling period", "months", "Cash-flow timing inputs."), input("Pre-sales at launch", "%", "Configured sales assumption."), estimate("Revenue, ROI, IRR & payback", "INR / % / months", "Cash-flow model; financial outcomes are forecasts.") ] },
  ] },
  { id: "deliver-esg", label: "Deliver & ESG", icon: ShieldCheck, modules: [
    { id: "compliance", name: "Compliance", icon: ShieldCheck, note: "Rule-by-rule checks and remaining headroom.", parameters: [input("Byelaw thresholds", "rule-specific", "Authority-specific limits and enabled rules."), computed("Pass/fail & headroom", "checks / ratio", "Configured checks are not statutory approval.") ] },
    { id: "urban-sustainability", name: "Green Building & ESG", icon: Leaf, note: "Carbon, sustainability and resilience scenarios.", parameters: [input("Green checklist & material factors", "points / factors", "Project evidence and emission factors."), estimate("Embodied carbon & green score", "tCO₂e / points", "Indicative assessment, not IGBC or GRIHA certification.") ] },
    { id: "data-health", name: "Data Reliability", icon: Gauge, note: "Completeness, freshness and consistency.", parameters: [computed("Input coverage & stale results", "% / status", "Checks input availability and version consistency, not engineering correctness.") ] },
    { id: "reports", name: "Reports", icon: FileText, note: "Project documents and quantity workbooks.", parameters: [computed("Project reports & BOQ workbook", "PDF / XLSX", "Generated project snapshots; engineer review required.") ] },
    { id: "collaboration", name: "Versions & Team", icon: History, note: "Project history and shared working.", parameters: [input("Team roles & saved versions", "access / revision", "Shared project access and version snapshots."), computed("Activity & scheme comparison", "history / deltas", "Recorded changes and comparisons of selected versions.") ] },
  ] },
];
export const WORKSPACE_MODULES = WORKSPACE_CATALOG.flatMap(group => group.modules);
export const PARAMETER_COUNT = WORKSPACE_MODULES.reduce((total, module) => total + module.parameters.length, 0);
